### ISSUE TITLE
Not able to install grid encoder. 

### ISSUE THREAD

**Issue by Bhavay-2001** [guochengqian/Magic123#28]
Hello authors. 

I tried to install the gridencoders from install_ext.sh file you mentioned. While downloading, it says that there is a problem with the package and not with pip. 
The problem I can see from the logs is that there is not a definite PyTorch version to install. gridencoder needs a different torch version other than what is present in the environment and that's why it cannot be downloaded. 

Here are the logs while downloading grid encoder.
Building wheel for gridencoder (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/gridencoder/setup.py", line 33, in <module>
          setup(
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/venv_magic123/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/venv_magic123/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/venv_magic123/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/venv_magic123/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/venv_magic123/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.1) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gridencoder
  Running setup.py clean for gridencoder
Failed to build gridencoder
Installing collected packages: gridencoder
  Running setup.py install for gridencoder ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for gridencoder did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      running install
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/gridencoder/setup.py", line 33, in <module>
          setup(
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/venv_magic123/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/venv_magic123/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/command/install.py", line 546, in run
          self.run_command('build')
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/venv_magic123/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/apps/anaconda3-2022.05/lib/python3.9/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/venv_magic123/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/ukhalid/hasan_work/Bhavay_work/Magic123/venv_magic123/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.1) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> gridencoder

note: This is an issue with the package mentioned above, not pip.

How to reproduce issue - 
I just ran source install.sh and it produced the same issue.

**Comment by guochengqian** [comment]
The detected CUDA version (12.1) mismatches the version that was used to compile

**Comment by guochengqian** [comment]
You can follow instructions from Stable DreamFusion to install.
