### ISSUE TITLE
Environment Setting problem

### ISSUE THREAD

**Issue by wooj0216** [guochengqian/Magic123#48]
Hi, thanks for your great work.
By the way, I'm getting the environment setting problem.
When I tried to install cubvh, I got some errors.
How can I fix it?

```python
# cubvh
git+https://github.com/ashawkey/cubvh
``` 
```python
Collecting git+https://github.com/ashawkey/cubvh
  Cloning https://github.com/ashawkey/cubvh to /tmp/pip-req-build-bvbrm4_f
  Running command git clone --filter=blob:none --quiet https://github.com/ashawkey/cubvh /tmp/pip-req-build-bvbrm4_f
  Resolved https://github.com/ashawkey/cubvh to commit d44ba080983c8d84eaf7578ed2b96944746b798a
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ninja in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from cubvh==0.1.0) (1.11.1.1)
Collecting pybind11 (from cubvh==0.1.0)
  Using cached pybind11-2.11.1-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: trimesh in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from cubvh==0.1.0) (4.0.10)
Requirement already satisfied: opencv-python in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from cubvh==0.1.0) (4.9.0.80)
Requirement already satisfied: torch in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from cubvh==0.1.0) (1.12.1)
Requirement already satisfied: numpy in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from cubvh==0.1.0) (1.26.3)
Requirement already satisfied: tqdm in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from cubvh==0.1.0) (4.66.1)
Requirement already satisfied: matplotlib in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from cubvh==0.1.0) (3.8.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from matplotlib->cubvh==0.1.0) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from matplotlib->cubvh==0.1.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from matplotlib->cubvh==0.1.0) (4.47.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from matplotlib->cubvh==0.1.0) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from matplotlib->cubvh==0.1.0) (23.2)
Requirement already satisfied: pillow>=8 in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from matplotlib->cubvh==0.1.0) (10.0.1)
Requirement already satisfied: pyparsing>=2.3.1 in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from matplotlib->cubvh==0.1.0) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from matplotlib->cubvh==0.1.0) (2.8.2)
Requirement already satisfied: typing_extensions in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from torch->cubvh==0.1.0) (4.9.0)
Requirement already satisfied: six>=1.5 in /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->cubvh==0.1.0) (1.16.0)
Using cached pybind11-2.11.1-py3-none-any.whl (227 kB)
Building wheels for collected packages: cubvh
  Building wheel for cubvh (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [114 lines of output]
      /tmp/pip-req-build-bvbrm4_f/setup.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      sh: 1: nvcc: not found
      Targeting C++ standard 14
      Couldn't find Eigen locally, downloading...
      Found eigen at ./eigen-3.3.7
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/cubvh
      copying cubvh/api.py -> build/lib.linux-x86_64-cpython-310/cubvh
      copying cubvh/__init__.py -> build/lib.linux-x86_64-cpython-310/cubvh
      running build_ext
      building '_cubvh' extension
      creating /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310
      creating /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp
      creating /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f
      creating /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src
      Emitting ninja build file /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] /usr/local/cuda/bin/nvcc  -I/tmp/pip-req-build-bvbrm4_f/include -I./eigen-3.3.7 -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/TH -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cvlab15/anaconda3/envs/magic123/include/python3.10 -c -c /tmp/pip-req-build-bvbrm4_f/src/api.cu -o /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src/api.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++14 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_cubvh -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      FAILED: /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src/api.o
      /usr/local/cuda/bin/nvcc  -I/tmp/pip-req-build-bvbrm4_f/include -I./eigen-3.3.7 -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/TH -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cvlab15/anaconda3/envs/magic123/include/python3.10 -c -c /tmp/pip-req-build-bvbrm4_f/src/api.cu -o /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src/api.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++14 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_cubvh -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      /tmp/pip-req-build-bvbrm4_f/src/api.cu:1:9: warning: #pragma once in main file
          1 | #pragma once
            |         ^~~~
      In file included from /tmp/pip-req-build-bvbrm4_f/src/api.cu:3:
      /tmp/pip-req-build-bvbrm4_f/include/cubvh/api.h:3:10: fatal error: Eigen/Dense: No such file or directory
          3 | #include <Eigen/Dense>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      [2/3] /usr/local/cuda/bin/nvcc  -I/tmp/pip-req-build-bvbrm4_f/include -I./eigen-3.3.7 -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/TH -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cvlab15/anaconda3/envs/magic123/include/python3.10 -c -c /tmp/pip-req-build-bvbrm4_f/src/bvh.cu -o /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src/bvh.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++14 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_cubvh -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      FAILED: /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src/bvh.o
      /usr/local/cuda/bin/nvcc  -I/tmp/pip-req-build-bvbrm4_f/include -I./eigen-3.3.7 -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/TH -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cvlab15/anaconda3/envs/magic123/include/python3.10 -c -c /tmp/pip-req-build-bvbrm4_f/src/bvh.cu -o /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src/bvh.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++14 --extended-lambda --expt-relaxed-constexpr -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -Xcompiler=-Wno-float-conversion -Xcompiler=-fno-strict-aliasing -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_cubvh -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
      In file included from /tmp/pip-req-build-bvbrm4_f/src/bvh.cu:2:
      /tmp/pip-req-build-bvbrm4_f/include/cubvh/common.h:14:10: fatal error: Eigen/Dense: No such file or directory
         14 | #include <Eigen/Dense>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      [3/3] c++ -MMD -MF /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src/bindings.o.d -pthread -B /home/cvlab15/anaconda3/envs/magic123/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/cvlab15/anaconda3/envs/magic123/include -fPIC -O2 -isystem /home/cvlab15/anaconda3/envs/magic123/include -fPIC -I/tmp/pip-req-build-bvbrm4_f/include -I./eigen-3.3.7 -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/TH -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cvlab15/anaconda3/envs/magic123/include/python3.10 -c -c /tmp/pip-req-build-bvbrm4_f/src/bindings.cpp -o /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src/bindings.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_cubvh -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src/bindings.o
      c++ -MMD -MF /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src/bindings.o.d -pthread -B /home/cvlab15/anaconda3/envs/magic123/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/cvlab15/anaconda3/envs/magic123/include -fPIC -O2 -isystem /home/cvlab15/anaconda3/envs/magic123/include -fPIC -I/tmp/pip-req-build-bvbrm4_f/include -I./eigen-3.3.7 -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/TH -I/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cvlab15/anaconda3/envs/magic123/include/python3.10 -c -c /tmp/pip-req-build-bvbrm4_f/src/bindings.cpp -o /tmp/pip-req-build-bvbrm4_f/build/temp.linux-x86_64-cpython-310/tmp/pip-req-build-bvbrm4_f/src/bindings.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_cubvh -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from /tmp/pip-req-build-bvbrm4_f/src/bindings.cpp:5:
      /home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/include/pybind11/eigen.h:36:10: fatal error: Eigen/Core: No such file or directory
         36 | #include <Eigen/Core>
            |          ^~~~~~~~~~~~
      compilation terminated.
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
          subprocess.run(
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-bvbrm4_f/setup.py", line 154, in <module>
          setup(
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/cvlab15/anaconda3/envs/magic123/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cubvh
  Running setup.py clean for cubvh
Failed to build cubvh
ERROR: Could not build wheels for cubvh, which is required to install pyproject.toml-based projects
```

**Comment by guochengqian** [comment]
install: pip install pyproject-toml
